import unittest
from utils.java_compat import java_arrays_byte_hashcode

class TestJavaCompat(unittest.TestCase):
   
    def test_java_arrays_byte_hashcode(self):
        # 30817 generated by calling "Arrays.hashCode(byteArrayOf(1, 2, 3))" in kotlin (ran also equivalent in java)
        self.assertEqual(java_arrays_byte_hashcode(bytes([1, 2, 3])), 30817)
    
if __name__ == '__main__':
    unittest.main()