from enum import IntEnum, auto


class CliMethods(IntEnum):
    canceloffer = auto()
    closetrade = auto()
    confirmpaymentreceived = auto()
    confirmpaymentstarted = auto()
    createoffer = auto()
    editoffer = auto()
    createpaymentacct = auto()
    createcryptopaymentacct = auto()
    getavgbsqprice = auto()
    getaddressbalance = auto()
    getbalance = auto()
    getbtcprice = auto()
    getfundingaddresses = auto()

    # getmyoffer Deprecated Since 27-Dec-2021
    getmyoffer = auto()
    """Endpoint to be removed from future version.  Use getoffer instead."""

    getmyoffers = auto()
    getnetwork = auto()
    getoffer = auto()
    getoffers = auto()
    getpaymentacctform = auto()
    getpaymentaccts = auto()
    getpaymentmethods = auto()
    gettrade = auto()
    gettrades = auto()
    failtrade = auto()
    unfailtrade = auto()
    gettransactions = auto()
    gettransaction = auto()
    gettxfeerate = auto()
    getunusedbsqaddress = auto()
    getversion = auto()
    lockwallet = auto()
    registerdisputeagent = auto()
    removewalletpassword = auto()
    sendbsq = auto()
    sendbtc = auto()
    verifybsqsenttoaddress = auto()
    settxfeerate = auto()
    setwalletpassword = auto()
    takeoffer = auto()
    unlockwallet = auto()
    unsettxfeerate = auto()
    withdrawfunds = auto()
    stop = auto()
    getdaostatus = auto()
    confirmpaymentstartedxmr = auto()

    # bisq light specific
    sendproto = auto()
